# Generated by Django 4.0 on 2022-02-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enroll.basemodel')),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
            bases=('enroll.basemodel',),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enroll.basemodel')),
                ('roll', models.IntegerField()),
                ('date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.teachermodel')),
            ],
            bases=('enroll.basemodel',),
        ),
    ]
